[pytest]
minversion = 7.0
addopts =
    --strict-markers
    --html=reports/html/report.html
    --self-contained-html
    --junitxml=reports/junit/results.xml
    -ra

testpaths = tests

markers =
    ui: UI automation tests (Playwright)
    api: API automation tests (requests)

python_files = test_*.py
python_classes = Test*
python_functions = test_*

filterwarnings =
    ignore::DeprecationWarning

log_cli = false
log_level = INFO