[pytest]
minversion = 7.0
addopts =
    --strict-markers 
    --html=reports/html/report.html 
    --self-contained-html 
    --junitxml=reports/junit/results.xml 
    -ra 
    --tb=short 
    -v 
    --strict-config 

testpaths = tests

markers =
    ui: UI automation tests (Playwright)
    api: API automation tests (requests)
    smoke: Critical tests for basic functionality
    regression: Tests to ensure existing functionality still works
    sanity: Quick verification of a specific fix or feature
    unit: Unit tests
    integration: Integration tests
    e2e: End-to-end tests
    slow: Long-running tests
    fast: Quick-running tests
    database: Database-related tests
    auth: Authentication/Authorization tests
    positive: Positive test cases
    negative: Negative test cases
    performance: Performance/load-related tests
    security: Security-related tests

python_files = test_*.py
python_classes = Test*
python_functions = test_*

#ignores/skips deprecation warnings (meant to reduce noice in dev)
filterwarnings =
    ignore::DeprecationWarning  

#log messages not shown in CLI
log_cli = false 
# Min log level that pytest captures or displays.
log_level = INFO  
log_format = %(asctime)s | %(levelname)s | %(message)s
log_date_format = %Y-%m-%d %H:%M:%S
